---
name: IronSource Doc issue report
description: Problems and issues with IronSource documentation
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      # yamllint disable rule:line-length
      value: "
        <img src='https://raw.githubusercontent.com/ironSource/mobile-api-lib-python/main/docs/is_logo.jpg' align='left' width='80' height='80'>
        Thank you for finding the time to improve our documentation.

        **Please do not open an issue related to ironSource platform, sdk and etc. Only for ironSource API Library.**

        You do not have to create an issue if you have a pull request ready.

        You can open [Pull Request](https://github.com/ironSource/mobile-api-lib-python/pulls) immediately instead.
        <br clear='left'/>"
      # yamllint enable rule:line-length
  - type: textarea
    attributes:
      label: What do you see as an issue?
      description: Please describe the issue with documentation you have.
      placeholder: >
        Please include links to the documentation that has the problem and possibly screenshots showing
        the problem. Explain why do you think it is an issue. Please explain why you think the docs are wrong.
  - type: textarea
    attributes:
      label: Proposed documentation change
      description: How do you think the problem can be solved?
      placeholder: >
        Please explain how you think the documentation could be fixed.
  - type: checkboxes
    attributes:
      label: Are you willing to submit PR?
      description: >
        This is not required, but we will be happy if you would like to submit a pull-request.
      options:
        - label: Yes I am willing to submit a PR!
  - type: checkboxes
    attributes:
      label: Code of conduct
      description: By checking this checkbox you agree to ironSource [code of conduct](https://www.is.com)
      options:
        - label: I agree
          required: true
  - type: markdown
    attributes:
      value: "Thanks you!"